import React, { useEffect, useState } from "react";
import Navbar from "../navigator/navbar";
import Sidebar from "../navigator/sidebar";
import Head from "next/head";
import Cookies from "js-cookie";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const AdminLayout = ({ children }) => {
  const [user, setUser] = useState(null);

  useEffect(() => {
    const userCookie = Cookies.get("user");
    if (userCookie) {
      const parsedUser = JSON.parse(userCookie);
      setUser(parsedUser);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="h-screen">
        <Navbar />
        {user?.role.toLowerCase() === "admin" ? (
          <div className="flex-1 flex flex-row ">
            <Sidebar />
            <main className="  w-full flex-1 bg-[#d9d9d9]">{children}</main>
          </div>
        ) : (
          <main className=" container w-full flex-1 bg-[#000]">{children}</main>
        )}
      </div>
    </>
  );
};

export default AdminLayout;
